version: "3.9"

services:
  app:
    build: .
    container_name: github-node-gcp-cloud-run
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      DB_NAME: test
      DB_USER: root
      DB_PASSWORD: password
      DB_HOST: db
      PORT: 8080
    volumes:
      - .:/app
      - /app/node_modules